In [78]:
import numpy as np


theta = np.radians(90)


c, s = np.cos(theta), np.sin(theta)
ci, si = np.cos(-theta), np.sin(-theta)

rot_y = np.matrix([
        [ci, 0, si, 0],
        [0,  1, 0,  0],
        [-si,0, ci, 0],
        [0,  0,  0, 1]
    ])

rot_z = np.matrix([
        [c, -s, 0, 0],
        [s,  c, 0, 0],
        [0,  0, 1, 0],
        [0,  0, 0, 1]
    ])

rot_eye = np.eye(4)

rot_yz = rot_y.dot(rot_z)
rt = np.transpose(rot_yz)

rt = rt[0:3, 0:4]
print('rt = ', rt)



cx = 400
cy = 300

K = np.matrix([
        [1, 0, cx],
        [0, 1, cy],
        [0, 0, 1]
    ])

print('K = ', K)

point = np.array([1, 10, 10, 1])

# np.transpose(rot_yz).dot(point)
x = rt.dot(point)
# print('x1 = ', x)
x = np.reshape(x, (3,-1))
# print('x2 = ', x)
# x = rt.dot(point)
# x = point
print('x = ', x)

x[2] *= -1.0

uv = K.dot(x)
uv = np.reshape(uv, (3,-1))
print('uv = \n', uv)
uv = uv/uv[2]

print('uv = \n', uv)

# Normalize




rt =  [[  3.74939946e-33   1.00000000e+00   6.12323400e-17   0.00000000e+00]
 [ -6.12323400e-17   6.12323400e-17  -1.00000000e+00   0.00000000e+00]
 [ -1.00000000e+00   0.00000000e+00   6.12323400e-17   0.00000000e+00]]
K =  [[  1   0 400]
 [  0   1 300]
 [  0   0   1]]
x =  [[ 10.]
 [-10.]
 [ -1.]]
uv = 
 [[ 410.]
 [ 290.]
 [   1.]]
uv = 
 [[ 410.]
 [ 290.]
 [   1.]]
